framework:
    notifier:
        chatter_transports:
#            slack: '%env(SLACK_DSN)%'
            teams: '%env(TEAMS_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
        #texter_transports:
        #    twilio: '%env(TWILIO_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['chat/teams']
            high: ['chat/teams']
            medium: ['chat/teams']
            low: ['chat/teams']
        admin_recipients:
            - { email: admin@example.com }
